spring.application.name=mobile-banking

server.port=8888

spring.servlet.multipart.max-request-size=20MB
spring.servlet.multipart.max-file-size=10MB

media.server-path=C:/Users/PC/Pictures/MB-Banking/
media.base-uri=http://localhost:8888/media/

# configure bean of DataSource
spring.datasource.url=jdbc:postgresql://localhost:5432/mobile_banking
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=6229

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/mbapi

#spring.security.user.name = sadness
#spring.security.user.password=qwerqwer

#configure JPA Hibernate DDL
#Data Definition Language
#CREATE, ALTER, RENAME, ...
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true